/**
 * 动画常量配置
 */

// 动画时长（毫秒）
export const ANIMATION_DURATION = {
  FAST: 200,      // 快速动画
  NORMAL: 400,    // 正常动画
  SLOW: 600,      // 慢速动画
  VERY_SLOW: 1000, // 很慢的动画
};

// 缓动函数
export const EASING = {
  EASE_IN: 'cubic-bezier(0.4, 0, 1, 1)',
  EASE_OUT: 'cubic-bezier(0, 0, 0.2, 1)',
  EASE_IN_OUT: 'cubic-bezier(0.4, 0, 0.2, 1)',
  EASE: 'ease',
  LINEAR: 'linear',
};

// 卡片动画配置
export const CARD_ANIMATION = {
  MOVE_DURATION: ANIMATION_DURATION.NORMAL,
  MOVE_EASING: EASING.EASE_OUT,
  FADE_IN_DURATION: ANIMATION_DURATION.FAST,
  FADE_OUT_DURATION: ANIMATION_DURATION.FAST,
  SCALE_DURATION: ANIMATION_DURATION.FAST,
};

// 聚类动画配置
export const CLUSTER_ANIMATION = {
  EXPAND_DURATION: ANIMATION_DURATION.SLOW,
  EXPAND_EASING: EASING.EASE_OUT,
  COLLAPSE_DURATION: ANIMATION_DURATION.NORMAL,
  COLLAPSE_EASING: EASING.EASE_IN,
  STAGGER_DELAY: 50, // 卡片之间的延迟（毫秒）
};

// 布局动画配置
export const LAYOUT_ANIMATION = {
  REARRANGE_DURATION: ANIMATION_DURATION.NORMAL,
  REARRANGE_EASING: EASING.EASE_IN_OUT,
  FILL_GAP_DURATION: ANIMATION_DURATION.NORMAL,
  FILL_GAP_EASING: EASING.EASE_OUT,
};

